service: cadastro-pacientes

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  #region/stage
  stage: dev
  region: us-east-1

functions:
  listarPacientes:
    handler: handler.listarPacientes
